// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB7AOt_tblA7kuL4lyaWP_eJJFy7ps24U',
    appId: '1:250945452144:web:96c9156892ca202698dcb5',
    messagingSenderId: '250945452144',
    projectId: 'memoraapp-c5a0a',
    authDomain: 'memoraapp-c5a0a.firebaseapp.com',
    storageBucket: 'memoraapp-c5a0a.firebasestorage.app',
    measurementId: 'G-1YFY0H8WGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUpL1VPUAQmJK9RPbLYAGlQucezU7hyw',
    appId: '1:250945452144:android:e612ddfe8c8c0f3c98dcb5',
    messagingSenderId: '250945452144',
    projectId: 'memoraapp-c5a0a',
    storageBucket: 'memoraapp-c5a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxq-z0d0PgbGzrdo4nP4OIa6osQuus7s',
    appId: '1:250945452144:ios:62e40e11b1dfcefd98dcb5',
    messagingSenderId: '250945452144',
    projectId: 'memoraapp-c5a0a',
    storageBucket: 'memoraapp-c5a0a.firebasestorage.app',
    iosBundleId: 'com.example.memoraApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxq-z0d0PgbGzrdo4nP4OIa6osQuus7s',
    appId: '1:250945452144:ios:62e40e11b1dfcefd98dcb5',
    messagingSenderId: '250945452144',
    projectId: 'memoraapp-c5a0a',
    storageBucket: 'memoraapp-c5a0a.firebasestorage.app',
    iosBundleId: 'com.example.memoraApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB7AOt_tblA7kuL4lyaWP_eJJFy7ps24U',
    appId: '1:250945452144:web:7f000bc82522884198dcb5',
    messagingSenderId: '250945452144',
    projectId: 'memoraapp-c5a0a',
    authDomain: 'memoraapp-c5a0a.firebaseapp.com',
    storageBucket: 'memoraapp-c5a0a.firebasestorage.app',
    measurementId: 'G-83DNGW4LKD',
  );
}
